# Generated by Django 3.2.4 on 2021-07-07 12:55

from django.db import migrations, models
import topnotchdev.files_widget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', topnotchdev.files_widget.fields.ImagesField()),
            ],
        ),
        migrations.CreateModel(
            name='MyModelTwoFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', topnotchdev.files_widget.fields.ImagesField()),
                ('scene', topnotchdev.files_widget.fields.ImagesField()),
                ('place', models.CharField(max_length=255)),
            ],
        ),
    ]
