# Generated by Django 3.2.4 on 2021-06-22 08:35

from django.db import migrations, models
import topnotchdev.files_widget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', topnotchdev.files_widget.fields.ImagesField()),
            ],
        ),
    ]
